name: Helle
favicon: null
layout_spectrum: 0.2571
typography_spectrum: 0.8456998
title: Helles testblogg
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F3F2F1'
    - '#151319'
    - '#C6C4BF'
    - '#7F7064'
    - '#BE9177'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.9317032
  rhythmicContrast: 0.5
purpose: []
